"""Added recurring_interval

Revision ID: 0a76943f1fda
Revises: 7ef7943b458b
Create Date: 2025-01-19 18:09:04.400238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a76943f1fda'
down_revision: Union[str, None] = '7ef7943b458b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_tiers', sa.Column('recurring_interval', sa.String(), nullable=True))
    op.alter_column('subscription_tiers', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_tiers', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('subscription_tiers', 'recurring_interval')
    # ### end Alembic commands ###
