"""Changed Setup Steps

Revision ID: 5841a8aa94d0
Revises: ccb5c3d58063
Create Date: 2025-01-18 22:58:31.013744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5841a8aa94d0'
down_revision: Union[str, None] = 'ccb5c3d58063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
