"""Added MFA to Sessions

Revision ID: 5a8cd5a0feb1
Revises: 8828a93c4281
Create Date: 2025-01-23 19:25:10.247816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8cd5a0feb1'
down_revision: Union[str, None] = '8828a93c4281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('mfa_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'mfa_verified')
    # ### end Alembic commands ###
