"""Fix Notification foreign keys

Revision ID: 617332bb9b1a
Revises: 582c600c8a40
Create Date: 2025-02-02 21:51:45.203656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617332bb9b1a'
down_revision: Union[str, None] = '582c600c8a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
