"""Added Dynamic Subscriptions Modelsdw

Revision ID: 622c5784ac4d
Revises: 61e94342658b
Create Date: 2025-01-19 14:17:39.606858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622c5784ac4d'
down_revision: Union[str, None] = '61e94342658b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
