"""Changed Enumsadwdwdwd

Revision ID: 68074a181da1
Revises: 8312b26f3aac
Create Date: 2025-01-19 22:02:00.405815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68074a181da1'
down_revision: Union[str, None] = '8312b26f3aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
