"""Updating Models for User Settings

Revision ID: 727a2b36f74a
Revises: 5a8cd5a0feb1
Create Date: 2025-01-25 21:32:21.591450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727a2b36f74a'
down_revision: Union[str, None] = '5a8cd5a0feb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('device_type', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('location', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('last_activity', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()))
    op.add_column('users', sa.Column('push_notifications', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()))
    op.alter_column('users', 'email_notifications', server_default=None)
    op.alter_column('users', 'push_notifications', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_notifications')
    op.drop_column('users', 'email_notifications')
    op.drop_column('sessions', 'last_activity')
    op.drop_column('sessions', 'ip_address')
    op.drop_column('sessions', 'location')
    op.drop_column('sessions', 'device_type')
    # ### end Alembic commands ###
