"""Upgrade Subscri

Revision ID: 7ef7943b458b
Revises: 723789b3cbe7
Create Date: 2025-01-19 15:54:36.699029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef7943b458b'
down_revision: Union[str, None] = '723789b3cbe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_tiers', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_tiers', 'currency')
    # ### end Alembic commands ###
