"""Added MFA to User Models

Revision ID: 8828a93c4281
Revises: cc34b1092a0c
Create Date: 2025-01-22 17:42:19.717659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8828a93c4281'
down_revision: Union[str, None] = 'cc34b1092a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('mfa_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mfa_backup_codes', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('users', 'flagged_for_review',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'flagged_for_review',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'mfa_backup_codes')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    # ### end Alembic commands ###
