"""Add height_unit and weight_unit to User

Revision ID: e181c01a83ef
Revises: 5841a8aa94d0
Create Date: 2025-01-19 00:21:29.820905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e181c01a83ef'
down_revision: Union[str, None] = '5841a8aa94d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('height_unit', sa.String(), nullable=True))
    op.add_column('users', sa.Column('weight_unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight_unit')
    op.drop_column('users', 'height_unit')
    # ### end Alembic commands ###
