"""Updated Subscription tier

Revision ID: ee7edd5e9fe0
Revises: 622c5784ac4d
Create Date: 2025-01-19 14:49:06.616640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7edd5e9fe0'
down_revision: Union[str, None] = '622c5784ac4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_tiers', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('subscription_tiers', sa.Column('features', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('subscription_tiers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('has_ads', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('access_reels', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('reels_ad_free', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('access_workouts', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('workout_filters', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('access_community_read', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('access_community_post', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('private_community_challenges', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('access_nutrition', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('calorie_tracking', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('personalized_nutrition', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('direct_messaging', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('basic_progress_tracking', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('enhanced_progress_tracking', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('access_live_classes', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('one_on_one_coaching', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('priority_support', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('is_trial_available', sa.Boolean(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('trial_period_days', sa.Integer(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('billing_cycle', sa.String(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('cancellation_policy', sa.String(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('max_reel_uploads', sa.Integer(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('max_saved_workouts', sa.Integer(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('max_messages_per_day', sa.Integer(), nullable=True))
    op.drop_index('ix_subscription_tiers_id', table_name='subscription_tiers')
    op.drop_column('subscription_tiers', 'trial_days')
    op.drop_column('subscription_tiers', 'description')
    op.drop_column('subscription_tiers', 'price_cents')
    op.drop_column('subscription_tiers', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_tiers', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('subscription_tiers', sa.Column('price_cents', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subscription_tiers', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('subscription_tiers', sa.Column('trial_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_subscription_tiers_id', 'subscription_tiers', ['id'], unique=False)
    op.drop_column('subscription_tiers', 'max_messages_per_day')
    op.drop_column('subscription_tiers', 'max_saved_workouts')
    op.drop_column('subscription_tiers', 'max_reel_uploads')
    op.drop_column('subscription_tiers', 'cancellation_policy')
    op.drop_column('subscription_tiers', 'billing_cycle')
    op.drop_column('subscription_tiers', 'trial_period_days')
    op.drop_column('subscription_tiers', 'is_trial_available')
    op.drop_column('subscription_tiers', 'is_hidden')
    op.drop_column('subscription_tiers', 'priority_support')
    op.drop_column('subscription_tiers', 'one_on_one_coaching')
    op.drop_column('subscription_tiers', 'access_live_classes')
    op.drop_column('subscription_tiers', 'enhanced_progress_tracking')
    op.drop_column('subscription_tiers', 'basic_progress_tracking')
    op.drop_column('subscription_tiers', 'direct_messaging')
    op.drop_column('subscription_tiers', 'personalized_nutrition')
    op.drop_column('subscription_tiers', 'calorie_tracking')
    op.drop_column('subscription_tiers', 'access_nutrition')
    op.drop_column('subscription_tiers', 'private_community_challenges')
    op.drop_column('subscription_tiers', 'access_community_post')
    op.drop_column('subscription_tiers', 'access_community_read')
    op.drop_column('subscription_tiers', 'workout_filters')
    op.drop_column('subscription_tiers', 'access_workouts')
    op.drop_column('subscription_tiers', 'reels_ad_free')
    op.drop_column('subscription_tiers', 'access_reels')
    op.drop_column('subscription_tiers', 'has_ads')
    op.drop_column('subscription_tiers', 'is_active')
    op.drop_column('subscription_tiers', 'features')
    op.drop_column('subscription_tiers', 'price')
    # ### end Alembic commands ###
