"""Changed Enumsadwdwdwddwqdwfw

Revision ID: eef99f9ec2a6
Revises: 68074a181da1
Create Date: 2025-01-19 22:02:55.596469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef99f9ec2a6'
down_revision: Union[str, None] = '68074a181da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
