"""Added Dynamic Subscriptions Models

Revision ID: fc07c82ab912
Revises: c941f99cecc6
Create Date: 2025-01-19 14:11:33.478237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc07c82ab912'
down_revision: Union[str, None] = 'c941f99cecc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
